name: Deployment pipeline
on:
  push:
    branches:
      - main
jobs:
  simple_development_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-node@4
        with:
          node-version: '20'
      - name: Install dependences
        run: npm install
      - name: check style
        run: npm run eslint
